In [5]:
#import the necessary libararies
import pandas as pd 
import numpy as np 

In [6]:
df=pd.read_csv('cosmetic_p.csv')
df.head()

Label           brand                                           name  \
0  Moisturizer          LA MER                                Crème de la Mer   
1  Moisturizer           SK-II                       Facial Treatment Essence   
2  Moisturizer  DRUNK ELEPHANT                     Protini™ Polypeptide Cream   
3  Moisturizer          LA MER                    The Moisturizing Soft Cream   
4  Moisturizer    IT COSMETICS  Your Skin But Better™ CC+™ Cream with SPF 50+   

   price  rank                                        ingredients  \
0    175   4.1  Algae (Seaweed) Extract, Mineral Oil, Petrolat...   
1    179   4.1  Galactomyces Ferment Filtrate (Pitera), Butyle...   
2     68   4.4  Water, Dicaprylyl Carbonate, Glycerin, Ceteary...   
3    175   3.8  Algae (Seaweed) Extract, Cyclopentasiloxane, P...   
4     38   4.1  Water, Snail Secretion Filtrate, Phenyl Trimet...   

   Combination  Dry  Normal  Oily  Sensitive  
0            1    1       1     1          1  
1            1    1       1     1          1  
2            1    1       1     1          0  
3            1    1       1     1          1  
4            1    1       1     1          1

In [7]:

df=df.loc[:,['Label','brand','name','price','rank','ingredients']]

In [8]:
df['Label'].unique()

array(['Moisturizer', 'Cleanser', 'Treatment', 'Face Mask', 'Eye cream',
       'Sun protect'], dtype=object)

In [9]:
df.head(3)

Label           brand                        name  price  rank  \
0  Moisturizer          LA MER             Crème de la Mer    175   4.1   
1  Moisturizer           SK-II    Facial Treatment Essence    179   4.1   
2  Moisturizer  DRUNK ELEPHANT  Protini™ Polypeptide Cream     68   4.4   

                                         ingredients  
0  Algae (Seaweed) Extract, Mineral Oil, Petrolat...  
1  Galactomyces Ferment Filtrate (Pitera), Butyle...  
2  Water, Dicaprylyl Carbonate, Glycerin, Ceteary...

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [11]:
vector = cv.fit_transform(df['ingredients']).toarray()

In [12]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
vector.shape


(1472, 4456)

In [14]:
from sklearn.metrics.pairwise import cosine_similarity

In [15]:
similarity = cosine_similarity(vector)

In [16]:
similarity

array([[1.        , 0.10206207, 0.20007309, ..., 0.28141059, 0.07844645,
        0.        ],
       [0.10206207, 1.        , 0.31457643, ..., 0.12309149, 0.16012815,
        0.        ],
       [0.20007309, 0.31457643, 1.        , ..., 0.22010219, 0.12725695,
        0.        ],
       ...,
       [0.28141059, 0.12309149, 0.22010219, ..., 1.        , 0.17739372,
        0.        ],
       [0.07844645, 0.16012815, 0.12725695, ..., 0.17739372, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [17]:
df[df['name'] == 'Facial Treatment Essence'].index[0]

1

In [18]:
def moist_recommend(moist):
    index = df[df['name'] == moist].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(df.iloc[i[0]])

In [19]:
moist_recommend('Water Bank Dual Layer Face Oil')

Label                                                  Face Mask
brand                                                    LANEIGE
name           Water Pocket Sheet Mask Water Bank (Moisturizing)
price                                                          6
rank                                                         4.1
ingredients    Water, Dipropylene Glycol, Glycerin, 1,2-Hexan...
Name: 1066, dtype: object
Label                                                   Cleanser
brand                                                    LANEIGE
name           Essential Power Skin Toner for Combination to ...
price                                                         28
rank                                                         4.4
ingredients    Water, Alcohol, Glycereth-26, Dipropylene Glyc...
Name: 444, dtype: object
Label                                                Sun protect
brand                                                      FRESH
name                      Sugar Sport T

In [20]:
import pickle

In [21]:
pickle.dump(df.to_dict,open('skincare_dict.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [22]:
def display_only_that(brand):
    df_brand=df.loc[df['brand'] == brand]
   
    
    return df_brand

In [23]:
display_only_that('LA MER')

Label   brand                                               name  \
0     Moisturizer  LA MER                                    Crème de la Mer   
3     Moisturizer  LA MER                        The Moisturizing Soft Cream   
9     Moisturizer  LA MER  Little Miss Miracle Limited-Edition Crème de l...   
20    Moisturizer  LA MER                               Crème de la Mer Mini   
52    Moisturizer  LA MER                                    The Renewal Oil   
97    Moisturizer  LA MER                               The Concentrate Mini   
98    Moisturizer  LA MER                    The Moisturizing Cool Gel Cream   
162   Moisturizer  LA MER                       The Moisturizing Soft Lotion   
176   Moisturizer  LA MER                               The Renewal Oil Mini   
293   Moisturizer  LA MER                      The Moisturizing Matte Lotion   
315      Cleanser  LA MER                                 The Cleansing Foam   
355      Cleanser  LA MER                                          The Tonic   
405      Cleanser  LA MER                            The Cleansing Foam Mini   
413      Cleanser  LA MER                                  The Cleansing Gel   
502      Cleanser  LA MER                                  The Cleansing Oil   
545      Cleanser  LA MER                       The Cleansing Micellar Water   
587     Treatment  LA MER                                    The Concentrate   
601     Treatment  LA MER                             The Regenerating Serum   
613     Treatment  LA MER                   The Revitalizing Hydrating Serum   
619     Treatment  LA MER                               The Treatment Lotion   
636     Treatment  LA MER                           The Perfecting Treatment   
840     Face Mask  LA MER                       The Lifting and Firming Mask   
871     Face Mask  LA MER                    The Brilliance Brightening Mask   
940     Face Mask  LA MER                    Treatment Lotion Hydrating Mask   
957     Face Mask  LA MER                  The Lifting and Firming Mask Mini   
1045    Face Mask  LA MER                    The Intensive Revitalizing Mask   
1093    Eye cream  LA MER                                The Eye Concentrate   
1101    Eye cream  LA MER                               The Eye Balm Intense   
1120    Eye cream  LA MER                              The Lifting Eye Serum   
1361  Sun protect  LA MER      The Broad Spectrum SPF 50 UV Protecting Fluid   

      price  rank                                        ingredients  
0       175   4.1  Algae (Seaweed) Extract, Mineral Oil, Petrolat...  
3       175   3.8  Algae (Seaweed) Extract, Cyclopentasiloxane, P...  
9       325   5.0  Algae (Seaweed) Extract, Mineral Oil, Petrolat...  
20       85   4.1  Algae (Seaweed) Extract, Mineral Oil, Petrolat...  
52      245   4.2  Limnanthes Alba (Meadowfoam) Seed Oil, Dimethi...  
97      190   0.0  Cyclopentasiloxane, Algae (Seaweed) Extract, G...  
98      175   3.3                          Visit the La Mer boutique  
162     270   3.6  Algae (Seaweed) Extract, Petrolatum, Isocetyl ...  
176     130   4.0  Limnanthes Alba (Meadowfoam) Seed Oil, Dimethi...  
293     270   3.9  Water, Algae (Seaweed) Extract, Propanediol, S...  
315      95   4.3  Declustered Water (+)/Aqua/Eau De-Structuree (...  
355      95   4.1  Declustered Water (-)/Aqua/Eau De-Structuree (...  
405      25   5.0  Declustered Water (+)/Aqua/Eau De-Structuree (...  
413      95   4.2  Declustered Water (+)/Aqua/Eau De-Structuree (...  
502      95   4.3  Caprylic/Capric Triglyceride, Polysorbate 85, ...  
545      95   4.5  Declustered Water (-)/Aqua/Eau De-Structuree (...  
587     370   3.9  Cyclopentasiloxane, Algae (Seaweed) Extract, G...  
601     345   3.9  Water, Algae (Seaweed) Extract, Dimethicone, H...  
613     205   4.2  Declustered Water (-)/Aqua/Eau De-Structuree (...  
619     150   4.4  Declustered Water (+)/Aqua/Eau De-Structuree (...  
636     245   4.6  Water, Dimethicone, I

In [24]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [71]:
def Convert(string):
    li = list(string.split(","))
    return li

In [83]:
def similarity_between_ing(ing1,ing2):
    i1=[]
    i2=[]
    i1=ing1
    i2=ing2
    for i in i1:
        for j in i2:
            if (i==j):
                
                print(i)
        

    

In [72]:
ingre1=df['ingredients'].loc[df.index[315]]

In [73]:
type(ingre1)

str

In [74]:
g1=[]

In [75]:
g1=Convert(ingre1)

In [76]:
type(g1)

list

In [77]:
print(g1)

['Declustered Water (+)/Aqua/Eau De-Structuree (+)', ' Myristic Acid', ' Glycerin', ' Behenic Acid', ' Palmitic Acid', ' Sodium Methyl Cocoyl Taurate', ' Potassium Hydroxide', ' Lauric Acid', ' Stearic Acid', ' Algae (Seaweed) Extract', ' Sesamum Indicum (Sesame) Seed Oil', ' Medicago Sativa (Alfalfa) Seed Powder', ' Helianthus Annuus (Sunflower) Seedcake', ' Prunus Amygdalus Dulcis (Sweet Almond) Seed Meal', ' Eucalyptus Globulus (Eucalyptus) Leaf Oil', ' Sodium Gluconate', ' Copper Gluconate', ' Calcium Gluconate', ' Magnesium Gluconate', ' Zinc Gluconate', ' Tocopheryl Succinate', ' Niacin', ' Sesamum Indicum (Sesame) Seed Powder', ' Quartz Powder', ' Nephrite Powder', ' Pearl Powder', ' Caffeine', ' Sea Salt/Maris Sal/Sel Marin', ' Humic Acids', ' Sodium Hyaluronate', ' Sucrose', ' Tourmaline', ' Macrocystis Pyrifera (Kelp) Protein', ' Polyquaternium-51', ' Aloe Barbadensis Leaf Water', ' Trehalose', ' Cellulose', ' Butylene Glycol', ' Sodium Coco Pg-Dimonium Chloride Phosphate', '

In [78]:
ingre2=df['ingredients'].loc[df.index[413]]

In [79]:
type(ingre2)

str

In [80]:
g2=[]

In [81]:
g2=Convert(ingre2)

In [82]:
print(g2)

['Declustered Water (+)/Aqua/Eau De-Structuree (+)', ' Cocamidopropyl Hydroxysultaine', ' Sodium Cocoyl Sarcosinate', ' Coco-Betaine', ' Sodium Laureth Sulfate', ' Sodium Chloride', ' Aloe Barbadensis Leaf Extract', ' Avena Sativa (Oat) Kernel Extract', ' Algae (Seaweed) Extract', ' Sesamum Indicum (Sesame) Seed Oil', ' Medicago Sativa (Alfalfa) Seed Powder', ' Helianthus Annuus (Sunflower) Seedcake', ' Prunus Amygdalus Dulcis (Sweet Almond) Seed Meal', ' Eucalyptus Globulus (Eucalyptus) Leaf Oil', ' Sodium Gluconate', ' Copper Gluconate', ' Calcium Gluconate', ' Magnesium Gluconate', ' Zinc Gluconate', ' Tocopheryl Succinate', ' Niacin', ' Sesamum Indicum (Sesame) Seed Powder', ' Butylene Glycol', ' Sucrose', ' Caprylyl Glycol', ' Sodium Bicarbonate', ' Tourmaline', ' Hexylene Glycol', ' Fragrance', ' Edta', ' Disodium Edta', ' Methylchloroisothiazolinone', ' Methylisothiazolinone', ' Phenoxyethanol', ' Alpha-Isomethyl Ionone', ' Geraniol', ' Butylphenyl Methylpropional', ' Linalool',

In [84]:
similarity_between_ing(g1,g2)

Declustered Water (+)/Aqua/Eau De-Structuree (+)
 Algae (Seaweed) Extract
 Sesamum Indicum (Sesame) Seed Oil
 Medicago Sativa (Alfalfa) Seed Powder
 Helianthus Annuus (Sunflower) Seedcake
 Prunus Amygdalus Dulcis (Sweet Almond) Seed Meal
 Eucalyptus Globulus (Eucalyptus) Leaf Oil
 Sodium Gluconate
 Copper Gluconate
 Calcium Gluconate
 Magnesium Gluconate
 Zinc Gluconate
 Tocopheryl Succinate
 Niacin
 Sesamum Indicum (Sesame) Seed Powder
 Sucrose
 Tourmaline
 Butylene Glycol
 Sodium Bicarbonate
 Fragrance
 Disodium Edta
 Linalool
 Phenoxyethanol
 Methylchloroisothiazolinone
 Methylisothiazolinone
 Yellow 5 (Ci 19140)
 Green 5 (Ci 61570)
